# Generated by Django 5.0.7 on 2024-08-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FanState',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizersState',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeaterState',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LightState',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MistState',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True)),
                ('humidity', models.FloatField(blank=True)),
                ('soilMoisture', models.FloatField(blank=True)),
                ('lightLevel', models.FloatField(blank=True)),
                ('phLevel', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShadeState',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPumpState',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WaterState',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
